version: '3'

services:

  mysql-development:
    image: mysql:latest
    ports:
      - 3308:3306
    environment:
      # MYSQL_ROOT_PASSWORD: rodirgue1234 
      # MYSQL_DATABASE: testdb
      # MYSQL_USER: rodrigue
      # MYSQL_PASSWORD: rodirgue1234
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - .env
    # volumes:
    #   - mysql-development:/var/lib/mysql/data