FROM golang:latest

# LABEL maintainer="rodrigue <rodrigue2014@yahoo.fr>"

# WORKDIR /app-server

# COPY go.mod .

# COPY go.sum .

# RUN go mod download

# COPY . .

# ENV MYSQL_ROOT_PASSWORD rodrigue1234
# ENV MYSQL_DATABASE testdb
# ENV MYSQL_USER rodrigue
# ENV MYSQL_PASSWORD rodrigue1234
# ENV MYSQL_DB_HOST localhost
# ENV MYSQL_DB_PORT 3308
# ENV MYSQL_DB_PROTOCOL tcp
# ENV JWT_SECRET test

# RUN go build

# CMD [ "./VSM.git.exe" ]

